package ReverseModule;


/**
* ReverseModule/StringReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Monday, 28 April, 2025 5:04:17 PM IST
*/

public interface StringReverseOperations 
{
  String reverseString (String input);
} // interface StringReverseOperations
