package CaseChangeModule;

/**
* CaseChangeModule/StringOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CaseChange.idl
* Monday, 28 April, 2025 5:28:40 PM IST
*/

public final class StringOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public CaseChangeModule.StringOperations value = null;

  public StringOperationsHolder ()
  {
  }

  public StringOperationsHolder (CaseChangeModule.StringOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CaseChangeModule.StringOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CaseChangeModule.StringOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CaseChangeModule.StringOperationsHelper.type ();
  }

}
