package CaseChangeModule;


/**
* CaseChangeModule/StringOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CaseChange.idl
* Monday, 28 April, 2025 5:28:40 PM IST
*/

public interface StringOperations extends StringOperationsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringOperations
