package CaseChangeModule;


/**
* CaseChangeModule/StringOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CaseChange.idl
* Monday, 28 April, 2025 5:28:40 PM IST
*/

public interface StringOperationsOperations 
{
  String toUpperCase (String input);
} // interface StringOperationsOperations
