// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1745859864);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1745859841);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1745861768);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1745859984);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1745859894);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1745859834);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 116);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ef739eab-d5fe-42f7-b14a-61f67446a828}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1745859837);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1745861769632");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1745863546632");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1745859848810");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1745881448810");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210804193234");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1745861766");
user_pref("browser.startup.homepage_override.buildID", "20210804193234");
user_pref("browser.startup.homepage_override.mstone", "91.0");
user_pref("browser.startup.lastColdStartupCheck", 1745861766);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1745859838777");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "91.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IN");
user_pref("dom.push.userAgentID", "9fe7051a6c9a44e6ae3603370518f854");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210804193234");
user_pref("extensions.lastAppVersion", "91.0");
user_pref("extensions.lastPlatformVersion", "91.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"9dd6495b-3c46-41a9-a57c-097c0de579b2\",\"formautofill@mozilla.org\":\"4d65d536-6732-49a8-b4f5-cd9e55c7a8f6\",\"pictureinpicture@mozilla.org\":\"70ddb299-0026-4dae-93d2-914d6d3e2058\",\"screenshots@mozilla.org\":\"64e67dbd-52dc-45b4-9295-93e6932bd32d\",\"webcompat-reporter@mozilla.org\":\"a2dd1c49-4c36-46f5-87ad-d6d83f417fc7\",\"webcompat@mozilla.org\":\"4da2a354-3769-4dbf-a7fc-4c574237d614\",\"default-theme@mozilla.org\":\"05daa486-f831-4792-ba33-2310c3413e2a\",\"google@search.mozilla.org\":\"6b91e9cf-de31-4b01-b334-a8b6e6052ac7\",\"wikipedia@search.mozilla.org\":\"df28ef6a-f642-412c-aa6b-2a5c13ebac13\",\"bing@search.mozilla.org\":\"6636cee1-7c14-4ccb-a2ab-b076403cb7e9\",\"ddg@search.mozilla.org\":\"986b8507-ff8c-470b-bd33-961503b75b1e\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1745859838);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.decoder-doctor.MediaPlatformDecoderNotFound.formats", "video/mp4, video/mp4");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1745859890);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20210804193234");
user_pref("media.gmp-manager.lastCheck", 1745859887);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "4e155d59-75fa-4b12-bdc8-142d33968017");
user_pref("services.settings.clock_skew_seconds", 1881);
user_pref("services.settings.last_update_seconds", 1745859887);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1745859887);
user_pref("services.settings.main.sites-classification.last_check", 1745859887);
user_pref("toolkit.startup.last_success", 1745861765);
user_pref("toolkit.telemetry.cachedClientID", "1a05c587-4edd-4e48-98c3-b34b1c228a83");
user_pref("toolkit.telemetry.previousBuildID", "20210804193234");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
