// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.amount_written", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("calendar.list.sortOrder", "57897b15-f474-440c-9ee1-0282fa89d2da");
user_pref("calendar.registry.57897b15-f474-440c-9ee1-0282fa89d2da.calendar-main-in-composite", true);
user_pref("calendar.registry.57897b15-f474-440c-9ee1-0282fa89d2da.disabled", true);
user_pref("calendar.registry.57897b15-f474-440c-9ee1-0282fa89d2da.name", "Home");
user_pref("calendar.registry.57897b15-f474-440c-9ee1-0282fa89d2da.type", "storage");
user_pref("calendar.registry.57897b15-f474-440c-9ee1-0282fa89d2da.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "78.11.0");
user_pref("extensions.lastPlatformVersion", "78.11.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"ce9b0c8d-a465-41f3-829d-e81557e8b08f\",\"default-theme@mozilla.org\":\"f6064f4a-736b-4f15-a503-af078c42353e\",\"google@search.mozilla.org\":\"310e5588-bf7f-43a2-9e83-a787b57c2d5f\",\"amazondotcom@search.mozilla.org\":\"942ccc4f-4afc-4e89-a5d6-f5599a0c8e63\",\"bing@search.mozilla.org\":\"1e220373-bbe0-4cec-8a2e-8947c2a9cf9a\",\"ddg@search.mozilla.org\":\"b14ee902-39a1-4423-9239-fbaf2fb8ebe2\",\"wikipedia@search.mozilla.org\":\"727f869b-32e0-421b-9f8d-99f4b555cbe2\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 23);
user_pref("mailnews.database.global.datastore.id", "92e40bc6-36b5-4736-b14a-0f9d78a890a");
user_pref("mailnews.filters.migration78", true);
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "78.11.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("places.history.expiration.transient_current_max_pages", 15515);
user_pref("security.sandbox.plugin.tempDirSuffix", "f72e71c2-f81f-446b-b6a9-7948f3a5ac91");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "fca80761-2172-4c8b-bd85-bb3a356ed1ba");
user_pref("toolkit.telemetry.previousBuildID", "20210528153351");
