package ReverseModule;

/**
* ReverseModule/StringReverseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Monday, 28 April, 2025 5:04:17 PM IST
*/

public final class StringReverseHolder implements org.omg.CORBA.portable.Streamable
{
  public ReverseModule.StringReverse value = null;

  public StringReverseHolder ()
  {
  }

  public StringReverseHolder (ReverseModule.StringReverse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReverseModule.StringReverseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReverseModule.StringReverseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReverseModule.StringReverseHelper.type ();
  }

}
